// <auto-generated />
using System;
using Comment_Review_Downloader.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Comment_Review_Downloader.Migrations
{
    [DbContext(typeof(CommentsDbContext))]
    [Migration("20180807165308_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846");

            modelBuilder.Entity("Comment_Review_Downloader.Data.Entity.Amazon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateAdded");

                    b.Property<string>("Location");

                    b.Property<int>("NOC");

                    b.Property<string>("Name");

                    b.Property<DateTime?>("UpdatedDate");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.ToTable("Amazon");
                });

            modelBuilder.Entity("Comment_Review_Downloader.Data.Entity.YouTube", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateAdded");

                    b.Property<string>("Location");

                    b.Property<int>("NOC");

                    b.Property<string>("Name");

                    b.Property<DateTime?>("UpdatedDate");

                    b.Property<string>("YouTube_Id");

                    b.HasKey("Id");

                    b.ToTable("YouTube");
                });
#pragma warning restore 612, 618
        }
    }
}
